// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/trpc/:trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../web/src/server/routes/trpc/[trpc]').default>>>>
    }
    '/v1/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../web/src/server/routes/v1/hello').default>>>>
    }
  }
}
export {}